routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/


Route::group(['prefix' => LaravelLocalization::setLocale(), 'middleware' => ['localeSessionRedirect', 'localizationRedirect']], function () {
    Route::get('/', 'AdminController@dashboard');
    // Autenticazione
    Auth::routes();
    Route::get('logout', 'Auth\LoginController@logout');
});

Route::group(['prefix' => LaravelLocalization::setLocale(), 'middleware' => ['localeSessionRedirect', 'localizationRedirect', 'auth', 'property']], function () {
    Route::get('/', 'AdminController@dashboard');
    Route::any('/loadReservations', 'ApiController@loadReservations');
    Route::post('/getRate', 'ApiController@getRate');
    Route::post('/checkAvailability', 'ApiController@checkAvailability');
    Route::post('/checkAvailabilityRoom', 'ApiController@checkAvailabilityRoom');
    Route::post('/getDetails', 'ApiController@getDetails');
    Route::get('/getCustomers', 'ApiController@getCustomers');
    Route::get('/getDashboardData', 'ApiController@getDashboardData');
    Route::post('/moveReservation', 'ApiController@moveReservation');
    // Availability
    Route::post('/getAccomodationsAvailability', 'ApiController@getAccomodationsAvailability');
    Route::post('/getAvailability', 'ApiController@getAvailability');
    Route::post('/storeAvailability', 'ApiController@storeAvailability');
    Route::get('/getAvailabilityFromDate', 'ApiController@getAvailabilityFromDate');
    // MyAllocator
    Route::get('/myallocator/roomAvailabilityList', 'MyAllocatorController@RoomAvailabilityList');
    Route::get('/myallocator/BookingList', 'MyAllocatorController@BookingList');
    // Admin
    Route::group(['prefix' => 'admin'], function () {
        Route::get('/', 'AdminController@dashboard');
        Route::get('profile', 'AdminController@profile');
        Route::get('dashboard', 'AdminController@dashboard');
        Route::get('planning', 'AdminController@planning');
        Route::get('settings', 'SettingsController@index');
        Route::post('settings/update/{key}', 'SettingsController@update');
        Route::post('settings/hotel', 'SettingsController@hotel');
        Route::post('settings/payment/paypal', 'SettingsController@paypal');
        Route::post('settings/payment/stripe', 'SettingsController@stripe');
        Route::post('settings/currency', 'SettingsController@currency');
        Route::post('settings/credit_card', 'SettingsController@credit_card');
        Route::post('settings/my_allocator', 'SettingsController@my_allocator');
        Route::get('photo/{id}', 'RoomsTypeController@photo');
        Route::post('photoupload/{id}', 'RoomsTypeController@photoupload');
        Route::get('photodelete/{id}', 'RoomsTypeController@photodelete');
        Route::get('reservation/details/{id}', 'ReservationsController@details');
        Route::post('reservation/cancel', 'ReservationsController@cancel');
        Route::post('reservation/delete', 'ReservationsController@destroy');
        Route::get('reservation/fix', 'ReservationsController@fix');
        Route::get('reservation/mark-to-review/{id}', 'ReservationsController@mark_to_review');
        Route::get('reservation/mark-to-complete/{id}', 'ReservationsController@mark_to_complete');
        Route::get('reservation/agency/{id}', 'ReservationsController@agency');
        Route::post('reservation/agency/{id}', 'ReservationsController@agency');
        Route::get('reservation/customer/{id}', 'ReservationsController@customer');
        Route::post('reservation/customer/{id}', 'ReservationsController@customer');
        Route::get('reservation/note/{id}', 'ReservationsController@note');
        Route::post('reservation/note/{id}', 'ReservationsController@note');
        Route::get('reservation/discount/{id}', 'ReservationsController@discount');
        Route::post('reservation/discount/{id}', 'ReservationsController@discount');
        Route::post('reservation/adjustments/{id}', 'ReservationsController@adjustments');
        Route::get('reservation/adjustments/{id}', 'ReservationsController@adjustments');
        Route::get('reservation/guests/{reservation_id}/{id}', 'ReservationsController@guests');
        Route::post('reservation/guests/{reservation_id}/{id}', 'ReservationsController@guests');
        Route::any('reservation/accomodations/{reservation_id}', 'ReservationsController@accomodations');
        Route::get('reservation/accomodations/remove/{reservation_id}/{id}', 'ReservationsController@accomodations_remove');
        Route::get('reservation/register-deposit/{id}', 'ReservationsController@register_deposit');
        Route::post('reservation/register-deposit/{id}', 'ReservationsController@register_deposit');
        Route::get('reservation/register-payment/{id}', 'ReservationsController@register_payment');
        Route::post('reservation/register-payment/{id}', 'ReservationsController@register_payment');
        Route::get('reservations/get-reservations-from-myallocator', 'ReservationsController@get_reservations_from_myallocator');
        Route::get('reservation/email/{id}', 'ReservationsController@email');
        Route::get('payments/confirm/{id}/{reservation_id}', 'ReservationPaymentsController@confirm');
        Route::get('payments/delete/{id}/{reservation_id}', 'ReservationPaymentsController@delete');
        Route::get('adjustments/delete/{id}/{reservation_id}', 'AdjustmentsController@delete');
        Route::get('fragments/put/', 'FragmentController@put');
        Route::get('fragments/list/{group}', 'FragmentController@list');
        Route::post('fragments/update/{id}', 'FragmentController@update');
        Route::post('fragments/delete/{id}', 'FragmentController@delete');
        Route::resource('reservations', 'ReservationsController');
        Route::resource('rooms', 'RoomsController');
        Route::resource('rooms-type', 'RoomsTypeController');
        Route::resource('fees', 'FeesController');
        Route::resource('rate-type', 'RatesTypeController');
        Route::resource('customers', 'CustomersController');
        Route::resource('offerts', 'OffertsController');
        Route::resource('emails', 'EmailsController');
        Route::resource('extra', 'ExtraController');
        Route::resource('fragments', 'FragmentController');
        Route::resource('availability', 'AvailabilityController');
        Route::post('availability/store', 'AvailabilityController@store');
        //Route::get('availability', 'AvailabilityController@index');
        Route::post('/notifMarkAsRead', 'NotificationsController@MarkAsRead');

        Route::get('/clear-cache', function () {
            $exitCode = Artisan::call('cache:clear');
            return back()->with('message_success', 'Cache cleared');
        });

        //Reoptimized class loader:
        Route::get('/optimize', function () {
            $exitCode = Artisan::call('optimize');
            return back()->with('message_success', 'Reoptimized class loader');
        });

        //Clear Route cache:
        Route::get('/route-cache', function () {
            $exitCode = Artisan::call('route:cache');
            return back()->with('message_success', 'Route cache cleared');
        });

        //Clear View cache:
        Route::get('/view-clear', function () {
            $exitCode = Artisan::call('view:clear');
            return back()->with('message_success', 'View cache cleared');
        });

        //Clear Config cache:
        Route::get('/config-cache', function () {
            $exitCode = Artisan::call('config:cache');
            return back()->with('message_success', 'Clear Config cleared');
        });
    });
});

Route::group(['prefix' => LaravelLocalization::setLocale(), 'middleware' => ['localeSessionRedirect', 'localizationRedirect', 'propertyWeb']], function () {
    Route::get('{property}/', 'BookingController@index');
    Route::any('{property}/rooms-availability', 'BookingController@roomsAvailability');
    Route::any('{property}/rooms-details/', 'BookingController@roomsDetails');
    Route::any('{property}/validate-code', ['as' => 'validate-code', 'uses' => 'OffertsController@validateCode']);
    Route::any('{property}/payment', ['as' => 'payment', 'uses' => 'BookingController@payment']);
    Route::any('{property}/ticket', ['as' => 'ticket', 'uses' => 'BookingController@ticket']);
    // Auth Cliente
    Route::post('{property}/customer/login', 'CustomersController@login');
    Route::post('{property}/customer/register', 'CustomersController@register');
    Route::post('{property}/customer/password/reset', 'CustomersController@resetPassword');
    Route::post('{property}/customer/password/renew', 'CustomersController@renewPassword');
    Route::any('{property}/customer/password/update/{token}', 'CustomersController@updatePassword');
});

/* CART */
Route::group(['middleware' => ['web']], function () {

    Route::get('cart/get', 'ReservationCartController@get');
    Route::get('cart/add', 'ReservationCartController@add');
    Route::get('cart/update', 'ReservationCartController@update');
    Route::get('cart/remove', 'ReservationCartController@remove');
    Route::get('cart/destroy', 'ReservationCartController@destroy');
});

Route::group(['prefix' => LaravelLocalization::setLocale(), 'middleware' => ['localeSessionRedirect', 'localizationRedirect', 'web', 'propertyWeb']], function () {
    Route::get('{property}/paypal', ['as' => 'paypal', 'uses' => 'PaymentsController@paypal']);
    Route::get('{property}/payment-complete', ['as' => 'paymentComplete', 'uses' => 'PaymentsController@paymentComplete']);

app/Customers.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Support\Facades\DB;
use App\Scopes\PropertyScope;

class Customers extends Model
{
    //
    protected $table = 'customers';

    /**
     * The "booting" method of the model.
     *
     * @return void
     */
    protected static function boot()
    {
        parent::boot();

        static::addGlobalScope(new PropertyScope);
    }

    public function search($query, $keyword)
    {
        if ($keyword!='') {
            $query->where(function ($query) use ($keyword) {
                $query->where("name", "LIKE", "%$keyword%")
                        ->orWhere("surname", "LIKE", "%$keyword%")
                        ->orWhere("email", "LIKE", "%$keyword%")
                        ->orWhere("phone", "LIKE", "%$keyword%");
            });
        }
        return $query;
    }
}

resources/views/admin/customers/create.blade.php
@extends('admin.main')

@push('styles')

@endpush

@section('page-header')
  <div class="row">
    <div class="col-sm-6">
      <h4 class="mt-0 mb-5">Create a new Customer</h4>
      <ol class="breadcrumb mb-0">
        <li><a href="{{url('/admin')}}">Home</a></li>
        <li><a href="{{url('/admin/customers')}}">Customers</a></li>
        <li class="active">
            <span class="show-for-sr">Current: </span> New
        </li>
      </ol>
    </div>
    <div class="col-sm-6">
      @include('admin.includes.language')
    </div>
  </div>
@stop

@section('page-content')
    <div class="widget">
      <div class="widget-heading">
                  <h3 class="widget-title">Insert new Customer</h3>
      </div>
        <div class="widget-body">
            {!! Form::open(['route' => 'customers.store']) !!}
              @include('admin.includes.form.customer',['text_btn'=> trans('admin.add')])
            {!! Form::close() !!}
        </div>
    </div>
    @push('script')
    <script>
        $('select[name="country"]').chosen();
    </script>
    @endpush

@stop

resources/views/admin/customers/edit.blade.php
@extends('admin.main')

@push('styles')

@endpush

@section('page-header')
  <div class="row">
    <div class="col-sm-6">
      <h4 class="mt-0 mb-5">Edit a Customer</h4>
      <ol class="breadcrumb mb-0">
        <li><a href="{{url('/admin')}}">Home</a></li>
        <li><a href="{{url('/admin/customers')}}">Customers</a></li>
        <li class="active">
            <span class="show-for-sr">Current: </span> Edit
        </li>
      </ol>
    </div>
    <div class="col-sm-6">
      @include('admin.includes.language')
    </div>
  </div>
@stop

@section('page-content')
    <div class="widget">
      <div class="widget-heading">
                  <h3 class="widget-title">Edit customer</h3>
      </div>
        <div class="widget-body">
            {!! Form::model($customers,['method' => 'put', 'url' =>'admin/customers/'. $customers['id']])!!}
              @include('admin.includes.form.customer',['text_btn'=> trans('admin.edit')])
            {!! Form::close() !!}
        </div>
    </div>
    @push('script')
    <script>
        $('select[name="country"]').chosen();
    </script>
    @endpush

@stop

resources/views/admin/customers/show.blade.php
@extends('admin.main')

@push('styles')

@endpush

@section('search-bar')
  {!! Form::open(['url' => 'admin/customers/','method'=>'get','class'=>'mt-15 mb-15 pull-left hidden-xs']) !!}
    <div class="form-group has-feedback mb-0">
      <input type="text" aria-describedby="inputSearchFor" placeholder="{{trans('admin.search_for')}}" name="keyword" style="width: 200px" class="form-control rounded"><span aria-hidden="true" class="ti-search form-control-feedback"></span><span id="inputSearchFor" class="sr-only">(default)</span>
    </div>
  {!! Form::close() !!}
@endsection

@section('page-header')
  <div class="row">
    <div class="col-sm-6">
      <h4 class="mt-0 mb-5">Customers</h4>
      <ol class="breadcrumb mb-0">
        <li><a href="{{url('/admin')}}">Home</a></li>
        <li class="active">
            <span class="show-for-sr">Current: </span> List
        </li>
      </ol>
    </div>
    <div class="col-sm-6">
      @include('admin.includes.language')
    </div>
  </div>
@stop

@section('page-content')

        <a href="{{ url('admin/customers/create')}}" class="btn btn-primary">{{trans('admin.add')}}</a>
        <hr>
        <table id="customers-list" class="table table-striped table-bordered">
            <thead>
            <tr>
                <th>{{ trans('admin.name')}}</th>
                <th>{{ trans('admin.surname')}}</th>
                <th>{{ trans('admin.phone')}}</th>
                <th>{{ trans('admin.email')}}</th>
                <th>{{ trans('admin.country')}}</th>
                <th>{{ trans('admin.action')}}</th>
            </tr>
            </thead>
            <tbody>
            @if($customers)
                @foreach ($customers as $customer)
                    <tr>
                        <td>{{$customer->name}}</td>
                        <td>{{$customer->surname}}</td>
                        <td>
                            {{$customer->phone}}<br>
                            {{$customer->phone_2}}<br>
                            {{$customer->phone_3}}
                        </td>
                        <td>{{$customer->email}}</td>
                        <td>{{$customer->country}}</td>
                        <td>
                            <a href="{{route('customers.edit', $customer->id)}}" class="btn btn-success"><i class="fa fa-edit"></i></a>
                            {!! Form::open(['method' => 'DELETE','route' => ['customers.destroy', $customer->id], 'class' => 'inline']) !!}
                            {!! Form::submit(trans('admin.delete'), ['class' => 'btn btn-danger']) !!}
                            {!! Form::close() !!}
                        </td>
                    </tr>
                @endforeach
            @endif
            </tbody>
        </table>
        <div>
          {{ $customers->links() }}
        </div>

    @push('script')

    <script>
        $(window).load(function () {
            $('#customers-list').DataTable({
                responsive : true,
                paging: false,
                "bInfo" : false
            });
        });
    </script>
    @endpush

@stop